name: docs

on:
  push:
    branches:
      - uodate-docs
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install mkdocs==1.6.0 mkdocs-material==9.5.32 mkdocs-print-site-plugin==2.6.0
      - run: mkdocs gh-deploy --force